package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"time"

	"github.com/mattsolo1/grove-notebook/pkg/service"
	"github.com/spf13/cobra"
)

// NewGitCmd creates the `nb git` command and its subcommands.
func NewGitCmd(svc **service.Service, workspaceOverride *string) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "git",
		Short: "Manage Git repositories within notebook directories",
		Long:  `Provides commands for initializing and managing Git repositories directly within notebook storage locations.`,
	}

	cmd.AddCommand(newGitInitCmd(svc, workspaceOverride))
	return cmd
}

func newGitInitCmd(svc **service.Service, workspaceOverride *string) *cobra.Command {
	var globalRepo bool

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Initialize a Git repository in the current workspace's notebook directory",
		Long: `Initializes a Git repository in the notebook workspace directory for the current context.

This command performs three actions:
1. Runs 'git init' in the workspace's notebook directory (e.g., workspaces/my-project/).
2. Creates a '.gitignore' file with sensible defaults for notebook content.
3. Creates a '.grove/notebook.yml' marker file to identify this as a notebook repository.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			s := *svc

			// 1. Determine Target Directory
			var targetCtx string
			if globalRepo {
				targetCtx = "global"
			} else {
				targetCtx = *workspaceOverride
			}

			wsCtx, err := s.GetWorkspaceContext(targetCtx)
			if err != nil {
				return fmt.Errorf("getting workspace context: %w", err)
			}

			// Get the workspace directory from the paths.
			// The structure is .../workspaces/<name>/inbox, so the workspace dir is one level up from inbox.
			locator := s.GetNotebookLocator()
			samplePath, err := locator.GetNotesDir(wsCtx.NotebookContextWorkspace, "inbox")
			if err != nil {
				return fmt.Errorf("could not resolve notebook path: %w", err)
			}
			// Go up one level from inbox to get the workspace directory
			targetDir := filepath.Dir(samplePath)

			fmt.Printf("Targeting notebook directory: %s\n", targetDir)

			// 2. Initialize Git Repository
			gitDir := filepath.Join(targetDir, ".git")
			if _, err := os.Stat(gitDir); err == nil {
				fmt.Println("Git repository already initialized.")
			} else {
				gitCmd := exec.Command("git", "init")
				gitCmd.Dir = targetDir
				if output, err := gitCmd.CombinedOutput(); err != nil {
					return fmt.Errorf("git init failed: %w\n%s", err, string(output))
				}
				fmt.Println("✓ Git repository initialized.")
			}

			// 3. Create .gitignore
			gitignorePath := filepath.Join(targetDir, ".gitignore")
			gitignoreContent := `# Generated by nb git init
.artifacts/
.grove-worktrees/

# OS files
.DS_Store
Thumbs.db

# Editor files
*.swp
.idea/
.vscode/
`
			if err := os.WriteFile(gitignorePath, []byte(gitignoreContent), 0644); err != nil {
				return fmt.Errorf("failed to write .gitignore: %w", err)
			}
			fmt.Println("✓ Created/updated .gitignore.")

			// 4. Create .grove/notebook.yml Marker
			groveDir := filepath.Join(targetDir, ".grove")
			if err := os.MkdirAll(groveDir, 0755); err != nil {
				return fmt.Errorf("failed to create .grove directory: %w", err)
			}
			markerContent := fmt.Sprintf("type: notebook\ncreated: %s\n", time.Now().Format(time.RFC3339))
			if err := os.WriteFile(filepath.Join(groveDir, "notebook.yml"), []byte(markerContent), 0644); err != nil {
				return fmt.Errorf("failed to create notebook marker: %w", err)
			}
			fmt.Println("✓ Created .grove/notebook.yml marker file.")

			fmt.Println("\nSuccess! Your notebook is now under Git version control.")
			return nil
		},
	}

	cmd.Flags().BoolVarP(&globalRepo, "global", "g", false, "Initialize in the global notebook instead of the current workspace's notebook")
	return cmd
}
